version: "3.5"

services:
  owntracks-recoder:
    image: hrshadhin/ot-recorder
    container_name: owntracks-recorder
    restart: unless-stopped
    volumes:
      - ${PWD}/config.yml:/app/config.yml
      - ${PWD}/data:/persist # only for sqlite
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Dhaka
