app:
  env: dev
  host:
  port: 8000
  read_timeout: 2s
  write_timeout: 5s
  idle_timeout: 3s
  context_timeout: 2s
  data_path: ./
  time_zone: 'Asia/Dhaka'
  debug: false

hook:
  telegram:
    secret_token: secret
    chat_id: -123

database:
  type: postgres
  host: localhost
  port: 5432
  name: owntracks_test
  username: dev
  password: dev
  ssl_mode: disable
  max_open_conn: 3
  max_idle_conn: 1
  max_life_time: 10s
  debug: false
