{
 "title": "Locations",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \nto_timestamp(created_at) as \"time\", lat, lon, acc as accuracy, vel as velocity\nFROM locations\nORDER BY created_at DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Battery %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \ncreated_at as time, batt\nFROM locations\nWHERE $__unixEpochFilter(created_at)\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Velocity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "rawSql": "SELECT \ncreated_at as time, vel\nFROM locations\nWHERE $__unixEpochFilter(created_at)\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Location Ping",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \nto_timestamp(created_at) as \"time\", lat, lon, acc as accuracy, vel as velocity \nFROM locations \nWHERE\n$__unixEpochFilter(created_at)\nORDER BY created_at desc"
    }
   ]
  }
 ]
}